/**
 * @author Kurok1 <im.kurokyhanc@gmail.com>
 * @since 1.2.1
 */
package ui

import _ "embed"

// queryResultsHTML is generated by ui/query-results and committed for Node-free Go builds.
//
//go:embed query-results.html
var queryResultsHTML string

// QueryResultsHTML returns the embedded MCP App document.
func QueryResultsHTML() string { return queryResultsHTML }
